### ISSUE TITLE
【代码规范】代码规范问题

### ISSUE THREAD

**Issue by Dywane** [jerrylai19990120/watermarker-mac-os#11]
- 方法调用需要保持一致
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/16508811/119864701-7d451b00-bf4d-11eb-89a8-1f43be212de3.png">

- 设计思路问题
  可以具体讲一下`watermark`和`imageMark`的关系吗？在我的理解，`watermark`应该包含`imageMark`？我看到代码`imageMark`又是一个`Watermark`类，很奇怪
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/16508811/119865079-df9e1b80-bf4d-11eb-85bb-32778a157fa6.png">

- 这部分代码应该是watermark初始化时候就附带的属性，而且我看不到其他地方有修改它们，为什么需要重复设置？
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/16508811/119865358-2c81f200-bf4e-11eb-8eae-9d0a1c1cb2c2.png"> 

- `WartermarkHandler`接口不够简介明了，有init、draw等接口，让人比较难以理解哪个方法应该什么时候调用，而且界面变化的处理也属于水印的逻辑，应该放到handler里面处理，而不是让VC处理
  假如我来写的话，接口我可能只会给出
  1. `- (void)showWatermarkWithRect:text:`
  2. `- (void)hideWatermark`
  
  这部分是我的建议，可以根据实际情况去处理

**Comment by jerrylai19990120** [comment]
watermark引起的疑惑已改为containerWindow, imageMark 已改为 waterMark。 containerWindow里面会包括waterMark。重复代码已修改。WaterMarkHandler里的接口简化成了removeWatermarks 和 showWatermarkWithRect:text:。
