### ISSUE TITLE
【接口设计】Watermark接口设计问题

### ISSUE THREAD

**Issue by Dywane** [jerrylai19990120/watermarker-mac-os#3]
```
+ (NSImage *)withView:(NSImageView *)view text:(NSString *)text
```

在这个方法中，需要传入一个`imageView`与`text`来生成一个`image`，但是方法的实现中，需要的只是：
<img width="772" alt="image" src="https://user-images.githubusercontent.com/16508811/119265510-9e3e0100-bc19-11eb-923a-8a5112fd4369.png">
而不是一个`imageView`，更好的接口设计应该是：

```
+ (NSImage *)withSize:(CGSize)size text:(NSString *)text
```

接口需要什么就传什么，不要传多余的东西，否则并不遵循SOLID原则

**Comment by jerrylai19990120** [comment]
接口已修复
