### ISSUE TITLE
【编码规范】尝试使用for in 代替C模式的for循环

### ISSUE THREAD

**Issue by Dywane** [jerrylai19990120/watermarker-mac-os#4]
**File: HomeVC.m**

<img width="980" alt="image" src="https://user-images.githubusercontent.com/16508811/119265736-5075c880-bc1a-11eb-811f-3b3cd1306aa3.png">

for in 循环能够直接拿到对应的`window`，而不需要通过index获取，这样更安全，而且代码量更少

**Comment by jerrylai19990120** [comment]
代码已修改
