### ISSUE TITLE
【bug】窗口水印问题

### ISSUE THREAD

**Issue by Dywane** [jerrylai19990120/watermarker-mac-os#6]
# 问题
- 会出现水印位置错误的问题，被提早截断
<img width="512" alt="image" src="https://user-images.githubusercontent.com/16508811/119515211-3e299500-bda8-11eb-94be-d1204942da6b.png">

- 窗口被遮蔽后，依然展示了水印
<img width="648" alt="image" src="https://user-images.githubusercontent.com/16508811/119515277-4f72a180-bda8-11eb-9829-93567ada20f1.png">

**Comment by jerrylai19990120** [comment]
bug已修改
