### ISSUE TITLE
【代码规范】代码规范建议

### ISSUE THREAD

**Issue by Dywane** [jerrylai19990120/watermarker-mac-os#8]
# 代码规范问题
- 方法名后应该添加空格：
  `- (void)removeWatermarks{` ❌
  `- (void)removeWatermarks {`✅

- 多个方法调用间需要添加空格
  `[[NSScreen mainScreen]frame]` ❌
  `[[NSScreen mainScreen] frame]`✅

- 参数与括号之间不需要空格
  `void MyAXObserverCallback( AXObserverRef observer )`❌
  `void MyAXObserverCallback(AXObserverRef observer)`✅

- 项目需要基本的mvc架构拆分，现在逻辑都在HomeVC处理，最好分出一个`WatermarkHandler `之类的，专门处理添加水印的操作

**Comment by jerrylai19990120** [comment]
已修改不规范代码和添加WatermarkHandler
